### ISSUE TITLE
Compiler error with warp 0.3.6

### ISSUE THREAD

**Issue by Danvil** [mkiefel/foxglove-ws#1]
Under linux I get the following compiler error. Strangely enough it compiles fine under Windows. This seems to happen with Rust 1.71 and 1.72.

```
error[E0698]: type inside `async fn` body must be known in this context
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/foxglove-ws-0.2.1/src/lib.rs:406:21
    |
406 |                     Ok(warp::reply::with_header(
    |                     ^^ cannot infer type for type parameter `E` declared on the enum `Result`
    |
note: the type is part of the `async fn` body because of this `await`
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/foxglove-ws-0.2.1/src/lib.rs:413:44
    |
413 |         warp::serve(foxglove_ws).run(addr).await;
    |                                            ^^^^^

For more information about this error, try `rustc --explain E0698`.
```

**Comment by Danvil** [comment]
I believe it happens when cargo chooses "warp" version 0.3.6 instead of 0.3.5.

**Comment by mkiefel** [comment]
Hey David. Thanks for the issue! I'll try to reproduce as soon as I can. We've been using this package quite a bit under Linux on x86-64 and arm64.

**Comment by mkiefel** [comment]
And indeed, I've been running it with 0.3.5 on one of the machines here.

**Comment by mkiefel** [comment]
Hey @Danvil, would you mind testing the change in #2? I did work for me. I now opted to explicitly mention the WebSocket sub-protocol name, rather than copying over the one from Foxglove.

**Comment by Danvil** [comment]
The reason for "works under Windows but not under Linux" was that my Windows system used `warp=0.3.5`, but on the Linux system after a fresh checkout cargo decided to use `warp=0.3.6`. Forcing it to use 0.3.5 solved the issue. So I guess a minor version number change in `warp` caused API incompatibility. I changed the title correspondingly.

Will try the fix once I get back to work, but I guess if it works for you with bump to `warp=0.3.6` the issue should be resolved.

**Comment by mkiefel** [comment]
Sounds good. Does indeed work with that version. Will bump the package on crates.io as well. Thanks again for the report.

**Comment by Danvil** [comment]
Awesome, thank you so much for the quick fix!
